/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "var(--color-background)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-container-low": "var(--color-surface-container-low)",
        "secondary-container": "var(--color-secondary-container)",
        "primary": "var(--color-primary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-container": "var(--color-primary-container)",
        "on-error-container": "var(--color-on-error-container)",
        "error": "var(--color-error)",
        "surface": "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-error": "var(--color-on-error)",
        "outline": "var(--color-outline)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "error-container": "var(--color-error-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-surface": "var(--color-on-surface)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "surface-bright": "var(--color-surface-bright)",
        "outline-variant": "var(--color-outline-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-background": "var(--color-on-background)",
        "secondary": "var(--color-secondary)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "48px",
        "container-margin": "24px",
        "unit": "8px",
        "gutter": "16px",
        "card-padding": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Geist"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Geist"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
