/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#131313",
        "on-tertiary-fixed-variant": "#38485d",
        "on-tertiary-container": "#2a3a4f",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#00201c",
        "surface-container-low": "#1c1b1b",
        "secondary-container": "#04b4a2",
        "primary": "#4edea3",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed-dim": "#4edea3",
        "inverse-primary": "#006c49",
        "on-surface-variant": "#bbcabf",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#10b981",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "surface": "#131313",
        "surface-dim": "#131313",
        "primary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "outline": "#86948a",
        "secondary-fixed-dim": "#4fdbc8",
        "surface-container-highest": "#353534",
        "on-secondary-fixed-variant": "#005048",
        "on-secondary-container": "#003f38",
        "error-container": "#93000a",
        "secondary-fixed": "#71f8e4",
        "on-primary": "#003824",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#0b1c30",
        "tertiary-container": "#94a4bd",
        "on-primary-container": "#00422b",
        "on-surface": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#213145",
        "on-secondary": "#003731",
        "surface-tint": "#4edea3",
        "on-primary-fixed": "#002113",
        "tertiary": "#b7c8e1",
        "tertiary-fixed": "#d3e4fe",
        "surface-container": "#201f1f",
        "surface-bright": "#3a3939",
        "outline-variant": "#3c4a42",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-background": "#e5e2e1",
        "secondary": "#4fdbc8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "48px",
        "container-margin": "24px",
        "unit": "8px",
        "gutter": "16px",
        "card-padding": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Geist"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Geist"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
